============================= test session starts ==============================
platform linux -- Python 3.13.2, pytest-8.3.3, pluggy-1.5.0
benchmark: 5.1.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=50 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /workspaces/gufo_snmp
configfile: pyproject.toml
plugins: benchmark-5.1.0
collected 3 items

benchmarks/test_v3_p4_getbulk.py ..F                                     [100%]

=================================== FAILURES ===================================
______________________________ test_pysnmp_async _______________________________

snmpd = <gufo.snmp.snmpd.Snmpd object at 0xffff9f8bf4d0>
benchmark = <pytest_benchmark.fixture.BenchmarkFixture object at 0xffff9f905d10>

    def test_pysnmp_async(snmpd: Snmpd, benchmark) -> None:
        from pysnmp.hlapi.v3arch.asyncio import (
            USM_AUTH_HMAC96_SHA,
            USM_KEY_TYPE_MASTER,
            USM_PRIV_CFB128_AES,
            ContextData,
            ObjectIdentity,
            ObjectType,
            SnmpEngine,
            UdpTransportTarget,
            UsmUserData,
            bulk_walk_cmd,
        )
    
        user_name = SNMP_USER.name
        privacy_key = SNMP_USER.priv_key.key.decode()
        auth_key = SNMP_USER.auth_key.key.decode()
    
        async def inner() -> None:
            async for x, y, z, var_binds in bulk_walk_cmd(
                SnmpEngine(),
                UsmUserData(
                    user_name,
                    authProtocol=USM_AUTH_HMAC96_SHA,
                    authKey=auth_key,
                    authKeyType=USM_KEY_TYPE_MASTER,
                    privProtocol=USM_PRIV_CFB128_AES,
                    privKey=privacy_key,
                    privKeyType=USM_KEY_TYPE_MASTER,
                ),
                await UdpTransportTarget.create((snmpd.address, snmpd.port)),
                ContextData(),
                0,
                25,
                ObjectType(ObjectIdentity(BASE_OID)),
            ):
                for i in var_binds:
                    i.prettyPrint()
    
>       @benchmark

benchmarks/test_v3_p4_getbulk.py:113: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.13/site-packages/pytest_benchmark/fixture.py:156: in __call__
    return self._raw(function_to_benchmark, *args, **kwargs)
/usr/local/lib/python3.13/site-packages/pytest_benchmark/fixture.py:180: in _raw
    duration, iterations, loops_range = self._calibrate_timer(runner)
/usr/local/lib/python3.13/site-packages/pytest_benchmark/fixture.py:318: in _calibrate_timer
    duration = runner(loops_range)
/usr/local/lib/python3.13/site-packages/pytest_benchmark/fixture.py:109: in runner
    function_to_benchmark(*args, **kwargs)
benchmarks/test_v3_p4_getbulk.py:115: in bench
    asyncio.run(run_async(inner()))
/usr/local/lib/python3.13/asyncio/runners.py:195: in run
    return runner.run(main)
/usr/local/lib/python3.13/asyncio/runners.py:118: in run
    return self._loop.run_until_complete(task)
/usr/local/lib/python3.13/asyncio/base_events.py:725: in run_until_complete
    return future.result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

fn = <coroutine object test_pysnmp_async.<locals>.inner at 0xffff9ce21560>

    async def run_async(fn):
>       tasks = [asyncio.create_task(fn()) for _ in range(CONCURRENCY)]
E       TypeError: 'coroutine' object is not callable

benchmarks/test_v3_p4_getbulk.py:38: TypeError

------------------------------------------------------------------------------------ benchmark: 2 tests -----------------------------------------------------------------------------------
Name (time in ms)             Min                 Max                Mean            StdDev              Median               IQR            Outliers     OPS            Rounds  Iterations
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_gufo_snmp_sync      154.6600 (1.0)      189.0708 (1.0)      160.7229 (1.0)      9.1721 (2.17)     157.2877 (1.0)      2.0380 (1.0)           8;9  6.2219 (1.0)          50           1
test_gufo_snmp_async     174.7698 (1.13)     193.2060 (1.02)     184.7190 (1.15)     4.2216 (1.0)      183.9731 (1.17)     6.7846 (3.33)         19;0  5.4136 (0.87)         50           1
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
=========================== short test summary info ============================
FAILED benchmarks/test_v3_p4_getbulk.py::test_pysnmp_async - TypeError: 'coro...
========================= 1 failed, 2 passed in 19.03s =========================
